//! # gantry-tlm — device-side telemetry facade
//!
//! The firmware-facing API for Gantry telemetry. One derive, one `send`, one macro:
//!
//! ```ignore
//! use gantry_tlm as tlm;
//!
//! #[derive(tlm::Telemetry)]
//! struct Imu {
//!     #[tlm(unit = "deg")] pitch: f32,
//!     #[tlm(unit = "dps")] gyro_y: f32,
//! }
//!
//! // once, at boot (RAM budget is the app's — you pass the ring size):
//! tlm::init!(bytes = 4096, clock = now_ticks, tick_hz = 1_000_000, device_id = "mr-wobbles", session = 0x1234);
//!
//! tlm::send(&Imu { pitch, gyro_y });   // one call, one timestamp, all fields
//! tlm!("hack.value", x);               // ad-hoc one-field packet "adhoc"
//!
//! // in the transport task:
//! let n = tlm::drain(&mut buf);        // hands out complete framed wire records
//! ```
//!
//! ## Framework-agnostic, no_std, alloc-free hot path
//!
//! No embassy, no tokio, no heap in the send path. Concurrency uses `critical-section` only
//! (the app selects an impl; `critical-section/std` on the host). The global pipeline encodes
//! [`gantry_wire`] records into a fixed ring buffer under a short critical section, drops the
//! oldest whole record when the ring is full (counted, and reported via `Stats` records), and
//! emits periodic `DeviceInfo`/`PacketDef`/`TimeSync`/`Stats` records on cadences driven by the
//! caller's [`drain`] frequency and the app-supplied timestamp fn — no timers, no deps.
//!
//! ## Zero-cost when disabled
//!
//! Crates default to **disabled**. Turn the machinery on with `features = ["enabled"]`
//! (firmware does `telemetry = ["gantry-tlm/enabled"]`). With `enabled` **off**:
//! `#[derive(Telemetry)]` expands to nothing, [`send`]/[`tlm!`]/[`drain`]/[`init!`] are inert
//! inline stubs, and arguments to `tlm!` are not evaluated. See `examples/zero_cost.rs`.

#![no_std]

pub use gantry_wire::Kind;

/// Re-export the derive macro. (`Telemetry` names both this macro and the trait below — they
/// live in different namespaces, exactly like `serde::Serialize`.)
pub use gantry_tlm_derive::Telemetry;

/// A field descriptor emitted by `#[derive(Telemetry)]`: name, kind, and unit (`""` if none).
#[derive(Clone, Copy, Debug)]
pub struct FieldDesc {
    pub name: &'static str,
    pub kind: Kind,
    pub unit: &'static str,
}

/// The visitor a [`Telemetry`] value pushes its field values into. The pipeline supplies a
/// concrete implementation that encodes straight into the wire ring — no reflection, no heap.
pub trait ValueWriter {
    fn field_f32(&mut self, v: f32);
    fn field_f64(&mut self, v: f64);
    fn field_i32(&mut self, v: i32);
    fn field_i64(&mut self, v: i64);
    fn field_bool(&mut self, v: bool);
    fn field_str(&mut self, v: &str);
}

/// Implemented by `#[derive(Telemetry)]`. A packet is a named group of fields written with a
/// single timestamp. `write_values` visits the fields in `FIELDS` order so encoding needs no
/// reflection; `id_cell` is a per-type static the pipeline uses to assign a packet id exactly
/// once.
pub trait Telemetry {
    /// Packet name (struct name snake-cased, unless `#[tlm(packet = "...")]`).
    const PACKET: &'static str;
    /// Field descriptors, in wire order.
    const FIELDS: &'static [FieldDesc];
    /// Visit each field value in `FIELDS` order.
    fn write_values<W: ValueWriter>(&self, w: &mut W);
    /// Per-type packet-id cell (`0` = unregistered). Generated by the derive.
    fn id_cell() -> &'static core::sync::atomic::AtomicU32;
}

/// A value usable with the [`tlm!`] macro. The kind is inferred from the Rust type.
pub trait AdhocValue {
    const KIND: Kind;
    fn write<W: ValueWriter>(self, w: &mut W);
}

macro_rules! impl_adhoc {
    ($t:ty, $k:ident, $m:ident) => {
        impl AdhocValue for $t {
            const KIND: Kind = Kind::$k;
            #[inline]
            fn write<W: ValueWriter>(self, w: &mut W) {
                w.$m(self);
            }
        }
    };
}
impl_adhoc!(f32, F32, field_f32);
impl_adhoc!(f64, F64, field_f64);
impl_adhoc!(i32, I32, field_i32);
impl_adhoc!(i64, I64, field_i64);
impl_adhoc!(bool, Bool, field_bool);
impl_adhoc!(&str, Str, field_str);

// ---------------------------------------------------------------------------------------------
// Enabled: the real pipeline.
// ---------------------------------------------------------------------------------------------
#[cfg(feature = "enabled")]
mod pipeline;
#[cfg(feature = "enabled")]
pub use pipeline::{drain, send, stats, DrainStats, RingCell, __adhoc, __init};

/// Register the global pipeline. `bytes` sizes the static ring buffer (RAM budget is yours);
/// `clock` is a `fn() -> u64` returning monotonic ticks; `tick_hz` is that clock's rate;
/// `device_id`/`session` identify the stream. Call once at boot. (Inert when disabled.)
#[cfg(feature = "enabled")]
#[macro_export]
macro_rules! init {
    (bytes = $n:expr, clock = $clock:expr, tick_hz = $hz:expr, device_id = $dev:expr, session = $sess:expr $(,)?) => {{
        static __GANTRY_TLM_RING: $crate::RingCell<{ $n }> = $crate::RingCell::new();
        $crate::__init(__GANTRY_TLM_RING.take(), $clock, $hz, $dev, $sess)
    }};
}

/// Ad-hoc single-field packet (named `"adhoc"`) with the field name and a value; the kind is
/// inferred from the value type (`f32`/`f64`/`i32`/`i64`/`bool`/`&str`). Each call site is its
/// own hidden packet. (Inert when disabled — the value is not evaluated.)
#[cfg(feature = "enabled")]
#[macro_export]
macro_rules! tlm {
    ($name:literal, $val:expr $(,)?) => {{
        static __GANTRY_TLM_ID: ::core::sync::atomic::AtomicU32 =
            ::core::sync::atomic::AtomicU32::new(0);
        $crate::__adhoc(&__GANTRY_TLM_ID, $name, $val);
    }};
}

// ---------------------------------------------------------------------------------------------
// Disabled: inert stubs. No machinery compiled, arguments to `tlm!`/`init!` not evaluated.
// ---------------------------------------------------------------------------------------------

/// Send a telemetry packet. Inert no-op when the `enabled` feature is off.
#[cfg(not(feature = "enabled"))]
#[inline(always)]
pub fn send<T>(_v: &T) {}

/// Drain complete framed records into `buf`, returning the byte count. Always `0` when disabled.
#[cfg(not(feature = "enabled"))]
#[inline(always)]
pub fn drain(_buf: &mut [u8]) -> usize {
    0
}

#[cfg(not(feature = "enabled"))]
#[macro_export]
macro_rules! init {
    ($($t:tt)*) => {{}};
}

#[cfg(not(feature = "enabled"))]
#[macro_export]
macro_rules! tlm {
    ($($t:tt)*) => {{}};
}
